template: templates/skin.erb.html

pages:
- app: 
    generate: app.html 
    views : 
        main: views/dashboard.html
- about: 
    generate: about.html
    views : 
        main: views/about.html

scripts:
- script:
    version: 1.0
    bundle:
     - scripts/air/AIRAliases.js
     - scripts/air/AIRIntrospector.js
     - scripts/libs/bootstrap.js
     - scripts/libs/knockout-2.1.0-min.js
     - scripts/libs/jquery.fn.custom.js
     - scripts/shared/data-persistance.js
     - scripts/shared/utils.js
     - scripts/presenters/global-presenter.js
     
stylesheets:
- style:
    version: 1.0
    bundle:
      - stylesheets/bootstrap.css
      - stylesheets/bootstrap-responsive.css
      - stylesheets/style.css