template: _layouts/hero.html
port: 8091

nav:
- structure:
    text: Structure
    url: structure.html
- bundles:
    text: Assets
    url: bundles.html
- deploy:
    text: Deploy
    url: deploy.html
- editor:
    text: Editor
    url: http://ipassexam.github.io/Air-Monkey/

