template: _templates/hero.html

pages:
- index: 
    generate: index.html 
    resource: _resources/index.yml
    views : 
        intro: _views/home-intro.erb
        main: _views/home-main.erb
- prerequisites:
    generate: prerequisites.html
    resource: _resources/prerequisites.yml
    views : 
        intro: _views/prerequisites-intro.erb
        main: _views/prerequisites-main.erb
- structure : 
    generate: structure.html
    resource: _resources/structure.yml
    views : 
        intro: _views/structure-intro.erb
        main: _views/structure-main.erb
- deploy: 
    generate: deploy.html
    resource: _resources/deploy.yml
    views : 
        intro: _views/deploy-intro.erb
        main: _views/deploy-main.erb

bundles:
- base:
    generate: scripts/base-v1.0.js
    files:
     - scripts/demo.js
- libraries-min:
    generate: scripts/libraries-min-v1.1.js
    files:
     - google-code-prettify/prettify.js
     - google-code-prettify/lang-yaml.js
     - scripts/bootstrap.js
- base:
    generate: stylesheets/base-v1.1.css
    files:
      - stylesheets/bootstrap.css
      - stylesheets/demo.css
      - stylesheets/bootstrap-responsive.css
      - google-code-prettify/sons-of-obsidian.css


