template: _templates/skin.erb.html # The website skin (erb template)
#rooturl: http://www.mywebsite.com/ #Whats the website root when published - All references in html ~/ will be replaced with this
# Define your pages here
pages:
- index: 
    generate: ~/index.html 
    navigation: Home
    title: My Homepage
    description: Meta description
    keywords: "CMS, S3, Ruby"
    views:
        intro: _views/home-intro.html
        main: _views/home-main.html
- about: 
    generate: ~/about.html
    navigation: About
    views:
        intro: _views/about-intro.html
        main: _views/about-main.html
- contact: #Pageless for nav only
    navigation: contact
    navigation_meta: contactform
    url: about:blank

# Define your bundles here (versioning is recomended if your caching assets)
bundles:
- script:
    generate: scripts/bootstrap.min-v2.1.1.js
    files:
     - scripts/bootstrap.js
- style:
    generate: stylesheets/style-1.0.css
    files:
      - stylesheets/bootstrap.css
      - stylesheets/bootstrap-responsive.css
      - stylesheets/style.css
